### ISSUE TITLE
Rake task conflict 

### ISSUE THREAD

**Issue by sivagollapalli** [codeodor/minitest-rspec_mocks#8]
After adding gem to my `Gemfile` whenever runs test with `rake test `  then it gives following error:
```
invalid option: --pattern

minitest options:
    -h, --help                       Display this help.
    -s, --seed SEED                  Sets random seed. Also via env. Eg: SEED=n rake
    -v, --verbose                    Verbose. Show progress processing files.
    -n, --name PATTERN               Filter run on /regexp/ or string.

Known extensions: pride
    -p, --pride                      Pride. Show your testing pride!
```

which leads my build fail. After debugging I commented out the rake task that has been defined in `Rakefile` this error vanished. Could you please help?

**Comment by codeodor** [comment]
Can you tell me the versions of minitest and rake that you're using so I can try to reproduce?

Thanks,
Sam

**Comment by sivagollapalli** [comment]
`rake 10.4.2`, `minitest 5.8.3`

**Comment by codeodor** [comment]
Are you using it straight from the git repo? Just wondering because the gemspec doesn't list the Rakefile as part of the package, so I thought if it's included, it will be strange.

**Comment by codeodor** [comment]
Also, are you using RSpec too? I see this seems similar: https://github.com/rspec/rspec-rails/issues/1171

**Comment by sivagollapalli** [comment]
@codeodor My gemfile didn't pointing to github repo. I am using as `gem minitest-rspec_mocks` on my `Gemfile`. 

Yes I am using `rspec-rails` too on my rails app. But https://github.com/rspec/rspec-rails/issues/1171 issue has been closed. Do you think this issue cropped because of `rspec` ?

**Comment by codeodor** [comment]
I think the issue cropped up because of something in rspec-rails and a combination of minitest, as noted in that issue. Their initial solution (if I recall correctly) was to remove whatever was causing minitest to autorun.

We recently removed that in https://github.com/codeodor/minitest-rspec_mocks/pull/7. So can you try using `gem 'minitest-rspec_mocks', github: 'codeodor/minitest-rspec_mocks'` just to see if the issue goes away?

If it does, then I think now will be a good time to release a new version with that fix.

If it does not work, then I wonder if we can double check that the `rspec-rails` version you're running includes the fix they finally added in that project?

**Comment by sivagollapalli** [comment]
Yeah!! it worked. Thanks for the fix.

**Comment by codeodor** [comment]
Thanks! I pushed out version 0.4.0 with this change.
